var umanage = [];
umanage["en"] = {
  "general": {
    "closeModule": "Close Umanage"
  },
  "errors": {
    "loadSingleUserError": "Whoops. A small error occurred while retrieving user data. Please try again, or ask for support at support@opsi.it",
    "newUserError": "Error creating a user.",
    "removeDeletedError": "An error occurred while trying to remove deleted users",
    "removeUnauthError": "An error occurred while trying to remove unauthorized users",
    "translationsLoadError": "Error loading translations.",
    "usersLoadError": "Error loading users."
  },
  "menuVertical": {
    "actions": "Actions",
    "authorized": "Show only unauth users",
    "confirmDeletionDeletedUser": "This action will permanently delete all deleted users. You cannot get back.",
    "confirmDeletionDeletedUserTitle": "Really?",
    "confirmDeletionUnauthUser": "This action will permanently delete all unauthorized users. You cannot get back.",
    "confirmDeletionUnauthUserTitle": "Really?",
    "dangerZone": "Danger zone",
    "dangerZoneRemoveDeleted": "Remove deleted users",
    "dangerZoneRemoveUnauthorized": "Delete unauthorized users",
    "deleted": "Show only deleted users",
    "email": "Email",
    "lessRoles": "Show less roles",
    "moreRoles": "Show all roles",
    "name": "Name",
    "newUser": "Add new user",
    "online": "Show online users",
    "reset": "Reset filters",
    "roles": "Filter by DNN Roles",
    "search": "Search",
    "status": "Filter by User Status",
    "title": "Filters",
    "unconfirmed": "Unconfirmed users",
    "searchHelp": "by email, lastname, name, displayname, username, userid"
  },
  "newUser": {
    "email": "User email address",
    "password": "Password",
    "roles": "Add roles to this user",
    "username": "Username"
  },
  "userDetail": {
    "actions": "General actions",
    "authorize": "Authorize user",
    "confirm": {
      "auth": "You can unauthorize this user in a second moment.",
      "authTitle": "Authorizing this user.",
      "reenable": "You can remove this user in a second moment.",
      "reenableTitle": "Re-enabling this user.",
      "remove": "You can re-enable this user in a second moment.",
      "removeTitle": "Removing this user.",
      "unauth": "This can be undone by authorizing this user.",
      "unauthTitle": "Unauthorizing this user."
    },
    "deleteUser": "Delete user",
    "displayName": "Display name",
    "email": "Email",
    "emailResetPassword": "Send reset password link",
    "name": "First name",
    "newUserCreatedSuccess": "You've done! Great!",
    "newUserCreatedTitle": "User successfully created!",
    "passwordConfirm": "Confirm password",
    "passwordManagement": "Password management",
    "passwordNew": "New password",
    "reenableUser": "Re-enable user",
    "saveNewUser": "Create new user",
    "security": "User security",
    "surname": "Last name",
    "unauthorize": "Unauthorize user",
    "updateUser": "Update user profile",
    "userInfo": "User data",
    "username": "Username (used when logging in)",
    "userRoles": "Role management",
    "userUpdatedSuccess": "You're awesome!",
    "userUpdatedTitle": "User updated successfully!"
  },
  "userFilters": {
    "browsingPage": "Browsing page",
    "browsingPageOf": "of",
    "fromPage": "Viewing page",
    "page": "View page",
    "registeredUsers": "total users",
    "toPage": "of",
    "order": {
      "displayname": "Display name",
      "email": "Email",
      "lastlogindate": "Last access",
      "lastname": "Lastname",
      "name": "Name",
      "regdate": "Creation date",
      "userid": "Userid",
      "username": "Username",
      "Ascending": "Ascending",
      "Descending": "Descending"
    }
  },
  "userTiles": {
    "actionsAvailable": "Actions available",
    "creationDate": "Creation date",
    "dnnEdit": "Full DNN edit",
    "email": "Email",
    "excelExport": "Excel Export",
    "fastEdit": "Fast edit",
    "impersonate": "Impersonate",
    "lastAccess": "Last access",
    "noUsersFound": "Sorry, it seems nobody's here.",
    "phone": "Phone",
    "userName": "DNN User Name",
    "firstName": "Firt Name",
    "lastName": "Last Name",
    "displayName": "Display Name",
  }
};

umanage["it"] = {
  "general": {
    "closeModule": "Chiudi Umanage"
  },
  "errors": {
    "loadSingleUserError": "Ops. Si è verificato un piccolo errore durante il recupero dei dati utente. Riprova, o chiedi supporto a support@opsi.it",
    "newUserError": "Errore durante la creazione dell'utente.",
    "removeDeletedError": "Si è verificato un errore durante il tentativo di rimuovere gli utenti eliminati",
    "removeUnauthError": "Si è verificato un errore durante il tentativo di rimuovere utenti non autorizzati",
    "translationsLoadError": "Error loading translations.",
    "usersLoadError": "Errore durante in caricamento degli utenti."
  },
  "menuVertical": {
    "actions": "Azioni",
    "authorized": "Visualizza solo utenti non autorizzati",
    "confirmDeletionDeletedUser": "Questa azione eliminerà definitivamente tutti gli utenti eliminati. Non si può tornare indietro.",
    "confirmDeletionDeletedUserTitle": "Davvero?",
    "confirmDeletionUnauthUser": "Questa azione eliminerà definitivamente tutti gli utenti non autorizzati. Non si può tornare indietro.",
    "confirmDeletionUnauthUserTitle": "Davvero?",
    "dangerZone": "Zona Pericolosa",
    "dangerZoneRemoveDeleted": "Rimuovi utenti eliminati",
    "dangerZoneRemoveUnauthorized": "Rimuovi utenti non autorizzati",
    "deleted": "Mostra solo gli utenti eliminati",
    "email": "Email",
    "lessRoles": "Mostra meno ruoli",
    "moreRoles": "Mostra tutti ruoli",
    "name": "Nome",
    "newUser": "Aggiungi nuovo utente",
    "online": "Visualizza utenti online",
    "reset": "Reimposta filtri",
    "roles": "Filtra per Ruoli DNN",
    "search": "Cerca",
    "status": "Filtra per stato utente",
    "title": "Filtri",
    "unconfirmed": "Utenti non confermati",
    "searchHelp": "per email, cognome, nome, nome visualizzato, nome utente, id utente"
  },
  "newUser": {
    "email": "Indirizzo Email",
    "password": "Password",
    "roles": "Aggiungere i ruoli a questo utente",
    "username": "Nome Utente"
  },
  "userDetail": {
    "actions": "Azioni generiche",
    "authorize": "Autorizza utente",
    "confirm": {
      "auth": "È possibile togliere le autorizzazioni a questo utente in un secondo momento.",
      "authTitle": "Autorizza questo utente.",
      "reenable": "È possibile rimuovere questo utente in un secondo momento.",
      "reenableTitle": "Riattiva questo utente.",
      "remove": "È possibile riattivare l'utente in un secondo momento.",
      "removeTitle": "Rimozione utente.",
      "unauth": "Questa azione può essere annullata autorizzando nuovamente questo utente.",
      "unauthTitle": "Togli autorizzazione utente."
    },
    "deleteUser": "Elimina utente",
    "displayName": "Nome visualizzato",
    "email": "Email",
    "emailResetPassword": "Invia Link Password Reset",
    "name": "Nome",
    "newUserCreatedSuccess": "Hai fatto! Grande!",
    "newUserCreatedTitle": "Utente creato con successo!",
    "passwordConfirm": "Conferma password",
    "passwordManagement": "Gestione password",
    "passwordNew": "Nuova password",
    "reenableUser": "Riabialita utente",
    "saveNewUser": "Crea nuovo utente",
    "security": "Sicurezza utente",
    "surname": "Cognome",
    "unauthorize": "Togli Autorizzazione Utente",
    "updateUser": "Aggiorna profilo utente",
    "userInfo": "Dati utente",
    "username": "Nome utente (usato durante il login)",
    "userRoles": "Gestione dei Ruoli",
    "userUpdatedSuccess": "Fantastico!",
    "userUpdatedTitle": "Utente aggiornato con Successo!"
  },
  "userFilters": {
    "browsingPage": "Sei a pagina",
    "browsingPageOf": "di",
    "fromPage": "Visualizza pagina",
    "page": "Vedi pagina",
    "registeredUsers": "utenti totali",
    "toPage": "di",
    "order": {
      "displayname": "Nome visualizzato",
      "email": "Email",
      "lastlogindate": "Ultimo Accesso",
      "lastname": "Cognome",
      "name": "Nome",
      "regdate": "Data Creazione",
      "userid": "Id Utente",
      "username": "Nome utente",
      "Ascending": "Ascendente",
      "Descending": "Discendente"
    }
  },
  "userTiles": {
    "actionsAvailable": "Azioni disponibili",
    "creationDate": "Data Creazione",
    "dnnEdit": "Modifica DNN Completa",
    "email": "Email",
    "excelExport": "Esporta in Excel",
    "fastEdit": "Modifica Rapida",
    "impersonate": "Impersona Utente",
    "lastAccess": "Ultimo Accesso",
    "noUsersFound": "Ci dispiace, sembra che non ci sia nessuno qui.",
    "phone": "Telefono",
    "userName": "Nome Utente DNN",
    "firstName": "Nome",
    "lastName": "Cognome",
    "displayName": "Nome Visualizzato",
  }
};
